# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_0UytQmDFZrKtYE_F9383m6V4rnwWA1
"""

import pandas as pd
import matplotlib.pyplot as plt
datos=pd.read_csv('https://raw.githubusercontent.com/brian-avila-contreras/trabajo_python_csv/main/Titanic%20-%20Titanic.csv.csv')
datos.head()

datos=pd.DataFrame(datos)
print(datos)

datos.isnull().sum()

plt.figure(figsize=(15,8))
fig, ax = plt.subplots()
ax.fill_between(datos.Age, datos.Ticket)
plt.title('ejes a comparar')
plt.xlabel('edad')
plt.ylabel('tickets')
plt.show()

plt.figure(figsize=(15,8))
fig, ax = plt.subplots()
ax.bar(datos.Age, datos.Ticket)
plt.title('ejes a comparar')
plt.xlabel('edad')
plt.ylabel('tickets')
plt.show()

media=datos.Fare.mean()
print(f'media en valor de tarifa euros es: {media:.2f}')

max=datos.Fare.max()
print(f'maximo en valor de tarifa euros es: {max:.2f}')

min=datos.Fare.min()
print(f'minimo en valor de tarifa euros es: {min:.2f}')

supervivencia = datos['Survived'].value_counts()
labels = ['No Sobrevivieron', 'Sobrevivieron']
colors = ['#ff9999','#66b3ff']
explode = (0.1, 0)

plt.figure(figsize=(8, 8))
plt.pie(supervivencia, labels=labels, colors=colors, explode=explode, autopct='%1.1f%%', startangle=90)
plt.title('Porcentaje de Supervivencia')
plt.show()

plt.figure(figsize=(10, 6))
plt.boxplot([datos[datos['Pclass'] == 1]['Fare'].dropna(),
             datos[datos['Pclass'] == 2]['Fare'].dropna(),
             datos[datos['Pclass'] == 3]['Fare'].dropna()],
            labels=['Primera Clase', 'Segunda Clase', 'Tercera Clase'])
plt.title('Distribución de Tarifas por Clase de Pasajero')
plt.xlabel('Clase de Pasajero')
plt.ylabel('Tarifa')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Cargar datos
datos = pd.read_csv('https://raw.githubusercontent.com/brian-avila-contreras/trabajo_python_csv/main/Titanic%20-%20Titanic.csv.csv')

# Agrupar por clase y sexo y contar el número de pasajeros
pasajeros_por_clase_sexo = datos.groupby(['Pclass', 'Sex']).size().unstack()

# Crear gráfico de barras
pasajeros_por_clase_sexo.plot(kind='bar', figsize=(10, 6))
plt.title('Número de Pasajeros por Clase y Sexo')
plt.xlabel('Clase de Pasajero')
plt.ylabel('Número de Pasajeros')
plt.xticks(rotation=0)
plt.legend(title='Sexo')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Cargar datos
datos = pd.read_csv('https://raw.githubusercontent.com/brian-avila-contreras/trabajo_python_csv/main/Titanic%20-%20Titanic.csv.csv')

# Crear gráfico de dispersión
plt.figure(figsize=(10, 6))
for survived in [0, 1]:
    subset = datos[datos['Survived'] == survived]
    plt.scatter(subset['Age'], subset['Fare'], label=f'Sobrevivió: {survived}', alpha=0.5)

plt.title('Relación entre Edad y Tarifa por Supervivencia')
plt.xlabel('Edad')
plt.ylabel('Tarifa')
plt.legend(title='Supervivencia')
plt.show()